summary: "TEST: Add 2 Numbers"
description: "This is a simple API which returns the sum of 2 numbers"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body" #cannot change
  name: "bodyy" #can change
  description: "Accepts a input dictionary of inputs x1 and x2"
  required: true
  schema:
    type: "object"
    properties:
      x1:
        type: "integer"
        format: "int64"
        example : 45
      x2:
        type: "integer"
        format: "int64"
        example : 45
responses:
  405:
    description: "Invalid input"
