version: '3.8'

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    image: "petsservice/fastapi:${IMAGE_TAG}"
    restart: always
    ports:
      - 11016:8800
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../sftp_upload_floder:/usr/src/app/sftp_upload_floder
      - ./log:/usr/src/app/log
      - ./dockerCliCert/ca.pem:/ca.pem
      - ./dockerCliCert/cert.pem:/cert.pem
      - ./dockerCliCert/key.pem:/key.pem
      - ./:/usr/src/app

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: redis.dockerfile
    image: "petsservice/redis:${IMAGE_TAG}"
    restart: always
    ports:
      - 6379:6379

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: celery_worker.dockerfile
    image: "petsservice/celery:${IMAGE_TAG}"
    restart: always
    depends_on:
      - redis
    volumes:
      - /home/privacy/deid_v2_PET/citc_v2/sourceCode/hadoop/dataMac:/home/hadoop/proj_/dataMac
      - /home/privacy/deid_v2_PET/citc_v2/sourceCode/hadoop/data_check:/home/hadoop/proj_/data_check
      - /home/privacy/deid_v2_PET/citc_v2/sourceCode/hadoop/data_error:/home/hadoop/proj_/data_error
      - /home/privacy/deid_v2_PET/citc_v2/sourceCode/hadoop/data:/home/hadoop/proj_/data
      - /home/privacy/deid_v2_PET/citc_v2/sourceCode/hadoop/final_project:/home/hadoop/proj_/final_project
      - ./:/usr/src/app

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: flower.dockerfile
    image: "petsservice/flower:${IMAGE_TAG}"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always
    ports:
      - 11026:5555
    depends_on:
      - celery