################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# EntryPoints configuration
################################################################
entryPoints:
  # web:
  #   address: ":80"
  
  fastapi:
    address: ":8800"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

################################################################
# Enabling ACME Data
################################################################
certificatesResolvers:
  myresolver:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # for test
      email: brucepan@itri.org.tw # the email same as the registered domain name
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
      # httpChallenge:
      #   entryPoint: web
      # dnsChallenge:
      #   provider: <DNS-PROVIDER-NAME>
      #   resolvers:
      #     - "<DNS-PROVIDER-IP:PORT>"
      #certificatesDuration: 168

################################################################
# Traefik logs configuration
################################################################
log:
  # Default: "ERROR"
  level: INFO
  
  # Sets the filepath for the traefik log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary.
  #
  # Optional
  # Default: os.Stdout
  #
  filePath: /etc/traefik/log/traefik.log

  # Format is either "json" or "common".
  #
  # Optional
  # Default: "common"
  #
  format: json

################################################################
# Access logs configuration
################################################################
# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
accessLog:
  # Sets the file path for the access log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary.
  #
  # Optional
  # Default: os.Stdout
  #
  filePath: /etc/traefik/log/access.log

  # Format is either "json" or "common".
  #
  # Optional
  # Default: "common"
  #
  format: json

################################################################
# Docker configuration backend
################################################################

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    # swarmMode: true
  file:
    filename: /etc/traefik/dynamic_conf.yml

################################################################
# Traefik Dashboard
################################################################
# The Dashboard has two modes: secure and insecure. 
# In the insecure mode, you can access the dashboard directly. 
# However, in the secure mode, you need to configure dynamic_conf.yml and routing.
# Ref.: https://doc.traefik.io/traefik/operations/dashboard/#the-dashboard

# api:
#   dashboard: true
#   insecure: true