version: '3.8'

services:
  nextjs:
    container_name: pets-web-dev
    build:
      context: .
      dockerfile: dev.dockerfile
    image: "${DOCKER_BUILD_IMAGE_NAME}:${DOCKER_BUILD_IMAGE_TAG}"
    restart: always
    ports:
    - 8081:8081
    volumes:
    - ./src:/app/src
    - .env:/app/.env
    - ../download_folder:/app/download_folder