version: "2"
services:
  web:
    # for syn
    #restart: always
    image: flask-redis_citc:05.1 #flask-redis_citc:04
    ports:
     - "5090:5088" 
     - "4421:22"
    volumes:
      - ./APP__:/app/app/devp
      - /etc/localtime:/etc/localtime:ro

    entrypoint: gunicorn
    command:  --log-level=debug --preload -w 1 -b 0.0.0.0:5088 app:app
    #command: ["/bin/bash","-c", "python app.py /app/sqljdbc4-2.0.jar > /app/app/devp/log/flask_log.txt"]
    environment:
      - REDIS_HOST:redis
      #-  REDIS_HOST:redis_compose
      - REDIS_PORT:6379
      - REDIS_PWD:"citcw200" 
    networks:
      mynetwork:
        ipv4_address: 172.126.1.7
        aliases: 
          - flask_compose 
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:4.0.1-alpine02
    ports:
     - "4420:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro  
    
    # environment:
    #   - PWD123:/run/secrets/my-pw2

    entrypoint: redis-server
    command:   --requirepass 'citcw200'

    networks:
      mynetwork:
        ipv4_address: 172.126.1.8
        aliases: 
          - redis_compose

  genSyncData_celery:
    # restart: always
    image: test/gan_celery:v1.0
    depends_on:
      - redis
    environment:
      - REDIS_HOST:redis
      #- REDIS_HOST:redis_compose
      - REDIS_PORT:6379
      - REDIS_PWD:"citcw200"        
    # command: ["/bin/bash","-c", "celery -A app.celery worker --loglevel=info -f /app/app/devp/log/celery_log.txt"]
    command: ["/bin/bash","-c", ". worker.sh"]
    volumes:
      # - /home/ubuntu/PETS/pets_dp/dp/de-identification:/de-identification
      - ./APP__:/app/app/devp
      - /etc/localtime:/etc/localtime:ro
    networks:
      mynetwork:
        ipv4_address: 172.126.1.9
        aliases: 
          - genSyncDataCelery_compose 

  #clone_keyMysql_nrt:
  #  # restart: always
  #  image: mariadb/peihsuan:10.3
  #  # user: root
  #  ports:
  #    - "11199:3306"
      # - "3222:22"
    #command: '--init-file /init.sql'
    #/bin/bash -c "mysql --default-character-set=utf8 -u root -pcitcw200 </key_db.sql"
    # command: ["/bin/bash","-c", ". start_ssh.sh"]
    # command: ["/bin/bash","-c", "mysql --default-character-set=utf8 -u root -pcitcw200 < var/lib/mysql/syn_db.sql"]
    
    #command: ['chown','root:root', '/start_ssh1.sh']
    #command: --init-file /key_db1.sql
    #command: ['service', 'ssh', 'start']
    #command: ["/usr/sbin/sshd", "-D"]
    #command: 'mysqld --default-authentication-plugin=mysql_native_password'
    # command: 'start_ssh1.sh'

  #  environment: 
  #    MYSQL_ROOT_PASSWORD: citcw200

  #  volumes:
  #    - '/etc/localtime:/etc/localtime:ro'
  #    - './APP__/keymariadb:/var/lib/mysql'
  #    - './initialDeIDServiceDBs_Tables.sh:/initialDeIDServiceDBs_Tables.sh'
      # - './keymariadb/syn_db.sql:/syn_db.sql'
      #- './start_ssh1.sh:/start_ssh1.sh'
      #- './init.sql:/init.sql'
    #stdin_open: true
    #tty: true
  #  networks:
  #    mynetwork:
  #      ipv4_address: 172.126.1.12  
  deidweb:
    restart: always
    image: pets_dp_deidweb:1.5 #pets_syn_deidweb:1.5 #pets_dp_deidweb:1.0  #syncweb_221:latest #syncweb:2.2
    ports:
      - "11065:11065"

    volumes:
      - ./appsettings.json:/app/appsettings.json
      # - process_appsettings.py:/app/process_appsettings.py
    networks:
      mynetwork:
        ipv4_address: 172.126.1.11

networks:
  mynetwork:
    external:
      name: hadoopnetDP
