version: "3.1"
services:
  nodemasterJ:
    restart: always
    image: pets_hadoop:1.2 #hive_nonroot:ub2004_ch_term_sshpass_P36 #hive_nonroot:ub2004_ch_termP36 #pets_hadoop:1.0 #hive_nonroot:pyarrow01_dmidecode_ch_term #hive_nonroot:pyarrow01_dmidecode
    hostname: nodemasterSJOIN

    secrets:
      - maria_file

    command: 'bash /start_all.sh'
    #user: hadoop
    #ports:
    #  - "6922:22"
      #- "5888:8888"
      #- "5188:8088"
      #- "5988:8088"
      #- "5199:8090"
      #- "5975:50075"
      #- "6970:50070"
      #docker service update CITCHadoop_nodemaster --publish-add 9970:50070
      #docker service update CITCHadoop_nodemaster --publish-add 9180:8088
      #docker service update CITCHadoop_nodemaster --publish-rm 9970:50070
      #docker service update  CITCHadoop_nodemaster --publish-rm 9180:8088
      #CITCHadoop_nodemaster

    #20210119 for sudo dmidecode baseboard-serial-number
    devices:
      - "/dev/mem:/dev/mem"
    #20210119 for sudo dmidecode baseboard-serial-number
    cap_add:
      - SYS_RAWIO

    volumes:
      - ./hive_conf:/home/hadoop/hive/conf
      - ./spark_conf:/home/hadoop/spark/conf
      - ./hadoop_conf:/home/hadoop/hadoop/etc/hadoop
      - ./masterCodeDir:/home/hadoop/proj_
      - ./data:/home/hadoop/proj_/data
      - ./dataMac:/home/hadoop/proj_/dataMac
      - ./masterDirN:/home/hadoop/data/nameNode

      #- ./sshd_config:/etc/ssh/sshd_config
      #2020010
      - ./masterDirD:/home/hadoop/data/dataNode
      #20240812
      #- ./ssh_conf:/home/hadoop/.ssh      
      - ./ssh_conf/config:/home/hadoop/.ssh/config
      
      #- /etc/localtime:/etc/localtime:ro
      - ./start_all.sh:/start_all.sh
      - ./start_hadoop.sh:/start_hadoop.sh
      - ./hadoop_bashrc:/home/hadoop/.bashrc
      #- ./dataConfig:/home/hadoop/proj_/dataConfig
    #command: bash -c "start-dfs.sh"
      #202109CFH
      #- ./data_bak:/home/hadoop/proj_/data_bak
      #- ./dataConfig_bak:/home/hadoop/proj_/dataConfig_bak
      #- ./data_check:/home/hadoop/proj_/data_check
      #- ./data_error:/home/hadoop/proj_/data_error
      - ./final_project:/home/hadoop/proj_/final_project
    #citc, for jQuery1.8 -> jQuery3.5 (rebuild hadoop-yarn-common-2.7.4.jar)
      - ./hadoop-yarn-common-2.7.4.jar:/home/hadoop/hadoop/share/hadoop/yarn/hadoop-yarn-common-2.7.4.jar
      #- /home/ubuntu/PETS/petsStartUp.sh:/home/hadoop/petsStartUp.sh  
      #- /home/ubuntu/PETS/cleaningMDB.sh:/home/hadoop/cleaningMDB.sh
      - ../../../../cleaningMDB.sh:/home/hadoop/cleaningMDB.sh
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime
      - ../../../../pets_dp/pets_dp/sourceCode/DP_webService/timezone:/etc/timezone        
    stdin_open: true
    tty: true

    networks:
      mynetwork:
       aliases:
          - nodemasterSJOIN


  psqlhmsJ:
    restart: always
    image: pets_hadoop_postgresql:1.0 #postgresql-hms:0.1
    hostname: psqlhmsSJOIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - './hiveMetaDB_postgre:/var/lib/postgresql/data'
    environment:
      - TZ=Asia/Taipei        
    networks:
      mynetwork:
        #ipv4_address: 172.28.0.16
        aliases:
          - psqlhmsSJOIN

  MariaDB_nrt:
    restart: always
    #image: mysql_ssh:5.7
    image: pets_mariadb:1.0 #mariadb/peihsuan:10.3
    hostname: MariaDB_nrtS
    #mariadb/peihsuan 10.3
    #user: root
    ports:
      - "11100:3306"
        #- "3323:22"
    #command: '--init-file /init.sql'
    #command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    
    #command: ['chown','root:root', '/start_ssh1.sh']
    #command: --init-file /key_db1.sql
    #command: ['service', 'ssh', 'start']
    #command: ["/usr/sbin/sshd", "-D"]
    #command: 'mysqld --default-authentication-plugin=mysql_native_password'
    command: 'bash /start_ssh1.sh'

    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './MariaDBdata:/var/lib/mysql'
      - './key_db1.sql:/key_db1.sql'
      - './start_ssh1.sh:/start_ssh1.sh'
      - './initialDeIDServiceDBs_Tables.sh:/initialDeIDServiceDBs_Tables.sh'
      #- './init.sql:/init.sql'
    #stdin_open: true
    #tty: true
    environment:
      - TZ=Asia/Taipei
    networks:
      mynetwork:
        #ipv4_address: 172.28.0.5
        aliases:
          - MariaDB_nrtS

secrets:
  maria_file:
    external: true
  hadoop_file:
    external: true


networks:
  mynetwork:
    external:
      name: hadoopnet_pet_overlay


#docker network create --subnet=172.88.1.0/16 hadoopnet_compose

#docker network create --subnet=172.98.8.0/16 hadoopnet_pet_overlay

#- "11600:3306" 
#- "6922:22"
# - "6970:50070"

